// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"omnikube/internal/config"
)

// Injectors from wire.go:

// InitializeApp 由 wire 生成实现（见 wire_gen.go）。
func InitializeApp(cfg *config.Config) (*App, error) {
	db, err := provideDB(cfg)
	if err != nil {
		return nil, err
	}
	jwtManager := provideJWT(cfg)
	cipher, err := provideCipher(cfg)
	if err != nil {
		return nil, err
	}
	clusterPool, err := providePool(db, cipher)
	if err != nil {
		return nil, err
	}
	service, err := provideRBAC(db, clusterPool)
	if err != nil {
		return nil, err
	}
	handler := provideHandler(db, jwtManager, clusterPool, service, cipher)
	engine := provideEngine(handler, jwtManager)
	app := provideApp(cfg, db, engine, clusterPool, service)
	return app, nil
}
